version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo *** working dir ***
      - pwd
      - echo *** before dir listing ***
      - ls -lR
  build:
    commands:
      - echo Build of tika started on `date`
      - gradle build --debug
  post_build:
    commands:
      - echo Build completed on `date`
      - echo *** after dir listing ***
      - ls -lR
artifacts:
  files:
    - ./build/distributions/tika-lambda.zip
